<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Build results</name>
  <uuid>8f009f95-e968-4b80-9db9-bb8dc9532f95</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to  'the extra bag fees' + 'the extra weight fees' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
