<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>salutation rule</name>
  <uuid>9633770c-712f-46eb-9eef-82c4c1d4029e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'the greeting' + " " + 'the courtesy title' + " " + the name of 'the customer' + "!" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
