<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print</name>
  <uuid>19e8b854-3fb3-4575-9a88-4c0914516112</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "With " + the number of Baggage Items in the bags of 'the checked baggage' +  " bags, the maximum allowed weight is " + decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
