<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Determine number of extra bags</name>
  <uuid>f3d9daac-d938-4501-8818-b749d113a5ad</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
 the number of elements in the bags of 'the checked baggage' 
    is more than the bags of 'the initial booking' 
then
    set decision to the number of elements in the bags of 'the checked baggage' - the bags of 'the initial booking' ;
else
    set  decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
