<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print</name>
  <uuid>dbb42774-9f4e-4fdf-b04f-b9a7141b5424</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "Extra bags: " + decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
