<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print</name>
  <uuid>335b5eb6-f484-4cd3-8c74-6399d2cfe4ea</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "Extra bags: " + decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
