<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print fees</name>
  <uuid>8055b1a6-437d-4de6-8273-99ed9d0e58df</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "Extra bag: " + decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
