<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Print fees</name>
  <uuid>cbb634fa-5cfd-43cf-958c-564b078ac38d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[print "Extra bag: " + decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
