<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Determine total weight</name>
  <uuid>778338b6-dcea-46b1-9a89-4680e6a5e73e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ;
for each Baggage Item called 'item' , in the bags of 'the checked baggage'  : 
    - set decision to decision + the weight of item , ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
