<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>15890abb-4e38-41d6-8093-e8c336a8a11a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'the name' to "Jones" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
